[profile.default]
rpc_url = "https://bsc-dataseed.binance.org/"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./script" },
    { access = "read-write", path = "./script/deployments" },
    { access = "read-write", path = "./script/deployments/addresses" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
